
path: '/content/gdrive/MyDrive/masters-CS-BIU/semester 2/advance AI/project'
train: images/train
val: images/train

# Classes
names:
  0: pig
  1: red_bird
  2: black_bird
  3: green_bird
  4: red_big_bird
  5: white_bird
  6: yellow_bird