
path: "/home/david/AIBirds/src/ab/python_agent/vision/dataset"
train:
  "images/train"
val:
  "images/val"

# Classes
names:
  0: pig
  1: reb_big_bird
  2: black_bird
  3: red_bird
  4: white_bird
  5: yellow_bird
  6: ice
  7: stone
  8: wood