
path: 'C:\Users\peleg\OneDrive\Desktop\masters\advance AI\project\abV1.32\abV1.32\src\ab\python_agent\vision\dataset'
train: images\train
val: images\val

# Classes
names:
  0: pig
  1: red_bird
  2: black_bird
  3: green_bird
  4: red_big_bird
  5: white_bird
  6: yellow_bird